# Generated by Django 5.1.6 on 2025-05-08 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='ingredients.ingredient')),
            ],
        ),
    ]
